### PR TITLE
0.30.0 of analyzer

### PR DESCRIPTION
**Pull request by devoncarew**
@jcollins-g, bump to 0.30.0 of analyzer

### CODE REVIEW

**Comment by devoncarew** [comment]
(updated to remove the dependency overrides)

**Comment by jcollins-g** [comment]
lgtm, but I'd prefer to punt on this until after we get something in for Flutter this week.

**Comment by devoncarew** [comment]
Sure, if you think this would introduce risk, I'll close this and you can upgrade after we push a release for flutter.

**Comment by jcollins-g** [comment]
Yeah, I think that's probably best for now -- all of my integration testing the last few days with flutter has been with that analyzer.  A week ago I would have said merge it but it's too close now.

**Pull request closed without merging**
