### PR TITLE
Update style for inherited members: dimmed and hidden

### PR DESCRIPTION
**Pull request by kevmoo**
Adding UI for this gets very expensive if you want to use MDL or similar
Just changing the style for now – should revisit adding dynamic feature
later

Closes https://github.com/dart-lang/dartdoc/issues/641

### CODE REVIEW

**Comment by kevmoo** [comment]
@sethladd @devoncarew @keertip Would love your feedback

Sample: http://kevmoo.github.io/dartdoc/dart-html/ButtonElement-class.html

**Comment by kevmoo** [comment]
A thought: we could apply this to *just* the links on the right of the page. It eases quick scanning, which is usually what I want here...

**Comment by Scorpiion** [comment]
Hi, I like this, I'm thinking if it would be beneficial to add a hover effect showing "Inherited member" for those dimmed links as well? Or would that be too much?

**Comment by sethladd** [comment]
lgtm

**Comment by keertip** [comment]
@kevmoo , looks good. Like your idea of applying this just to the right nav bar.

**Pull request merged**
