### PR TITLE
Switch dart:js and some dart:js_util usages to use static interop

### PR DESCRIPTION
**Pull request by parlough**
A little initial exploration into static JS interop to replace dartdoc's current usages of `dart:js` and some usages `dart:js_util`. This is closer to what JS-interop will likely look like in the future with inline classes, has some size benefits, and will make it easier to enable `strict-casts`.

Looks like there is even a little size decrease :D - 209244 bytes -> 201998 bytes or a ≈3.5% reduction when compiled with `-O4`.

### CODE REVIEW

**Comment by kevmoo** [comment]
@parlough – without loading the diff locally – what's the byte/% delta?

**Comment by parlough** [comment]
There's very few usages of the APIs here, so the reduction isn't too large: 209244 bytes -> 201998 bytes or a ≈3.5% reduction when compiled with `-O4`.

**Review by srawlins — APPROVED** [review]
This seems fine to me! The [staticInterop docs](https://pub.dev/documentation/js/latest/js/staticInterop-constant.html) are pretty ... slim. Are there benefits to this?

**Comment by kevmoo** [comment]
8K is a LOT for the small delta here! Awesome!

**Comment by kevmoo** [comment]
> This seems fine to me! The [staticInterop docs](https://pub.dev/documentation/js/latest/js/staticInterop-constant.html) are pretty ... slim. Are there benefits to this?

Yup - https://github.com/dart-lang/site-www/issues/4331

**Comment by parlough** [comment]
The README for package:js has some extra context too: https://github.com/dart-lang/sdk/tree/main/pkg/js#staticinterop

**Comment by srujzs** [comment]
Super cool to see the changes here, thanks for doing this!

**Comment by kevmoo** [comment]
@parlough – are you able to merge – or do you want me to do it?

**Comment by parlough** [comment]
@kevmoo I don't have commit access on dartdoc, so all you :)

**Pull request merged**
