### PR TITLE
Remove URI library

### PR DESCRIPTION
**Pull request by parlough**
This removes the `URI.js` library as modern browsers have built-in handling for getting query parameters and this library is 9.4 KB (28.4 uncompressed) for just one use.

While IE11 doesn't support this API, search functionality didn't work there in the first place nor did some other functionality, and this has feature detection, so shouldn't cause any errors if used in IE.

**Breaking change:** This removes the `URI.js` library from being included along with generated HTML documentation. While unlikely, downstream users may be using this.

### CODE REVIEW

**Comment by parlough** [comment]
I can update this after https://github.com/dart-lang/dartdoc/pull/2470 is merged or the other way around as well.

**Review by jcollins-g — APPROVED** [review]
Always happy to delete code, thanks!

**Comment by jcollins-g** [comment]
> I can update this after #2470 is merged or the other way around as well.

#2470 is merged

**Comment by parlough** [comment]
@jcollins-g This has been rebased on master and should be good to go :)

**Pull request merged**
