### PR TITLE
Support the latest version of pkg:analyzer

### PR DESCRIPTION
**Pull request by kevmoo**
Also bump pkg:coverage version

### CODE REVIEW

**Comment by devoncarew** [comment]
For the CI failures,I think you need to run `grind build`.

**Comment by kevmoo** [comment]
@devoncarew – green! feel free to squash/merge 😄

**Comment by devoncarew** [comment]
And one more issue:

```
check-changelog-has-version
  failed: ERROR: CHANGELOG.md does not mention version 0.28.5-dev
GrinderException: ERROR: CHANGELOG.md does not mention version 0.28.5-dev
```

**Comment by kevmoo** [comment]
Travis is green...right?

**Comment by devoncarew** [comment]
> Travis is green...right?

Sorry, I posted that in a page for the PR that was a few hours out of date.

**Pull request merged**
