### PR TITLE
sl-drawer-breadcrumbs

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
Addresses https://github.com/dart-lang/dartdoc/issues/736

**Comment by sethladd** [comment]
@devoncarew

**Comment by devoncarew** [comment]
lgtm!

q: why do you put the screenshots in the issue rather than the PR?

**Comment by sethladd** [comment]
> q: why do you put the screenshots in the issue rather than the PR?

I hadn't realized that, actually. :)  Whatever window was open?

PR makes more sense. Thanks for pointing that out!

**Pull request closed without merging**
