### PR TITLE
sl-inherited-methods

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @keertip @devoncarew

**Comment by sethladd** [comment]
So, this makes our builds CRAZY long because of how many files we create.

**Comment by keertip** [comment]
Do we still show an "inherited" to indicate whether a property or method it inherited?

**Comment by sethladd** [comment]
Yup! Check out the screenshot at https://github.com/dart-lang/dartdoc/issues/835

**Comment by sethladd** [comment]
Am fixing the build not to timeout.

**Comment by keertip** [comment]
Ok, looks good, once the travis build gets fixed!

**Comment by sethladd** [comment]
Also addresses https://github.com/dart-lang/dartdoc/issues/868

**Comment by sethladd** [comment]
Firebase is taking a long long time to upload.

**Comment by sethladd** [comment]
TBR

Please generate docs locally and see what you think.

**Pull request closed without merging**
