### PR TITLE
update version and changelog for recent changes

### PR DESCRIPTION
**Pull request by kevmoo**
[Review on Reviewable](https://reviewable.io/reviews/dart-lang/dartdoc/994)

### CODE REVIEW

**Comment by sethladd** [comment]
Did you get everything from https://github.com/dart-lang/dartdoc/issues?q=milestone%3A0.7.4+is%3Aclosed ?

**Comment by kevmoo** [comment]
I'll help cleanup the changelog more for 0.7.4 – I have a few more things coming

**Comment by keertip** [comment]
@kevmoo, planning to do a release today, so that I can get #996  into the sdk and have the docs building fine. Anything major, or can it wait?

**Comment by kevmoo** [comment]
@keertip Yup – although we should get the other items @sethladd mentioned into the changelog

**Pull request merged**
