### PR TITLE
Add missing overrides.

### PR DESCRIPTION
**Pull request by pq**
@keertip

### CODE REVIEW

**Comment by pq** [comment]
This passes locally and on travis.  @keertip : PTAL?

@devoncarew : I see that appveyor builds have been broken for a bit...  Any thoughts?

**Comment by devoncarew** [comment]
I did some work here to try and track it down, but didn't follow up: https://github.com/dart-lang/dartdoc/pull/1172

**Comment by pq** [comment]
Ah.  Maybe nailing this is something we can add to our fixit?

**Comment by pq** [comment]
@keertip : I think it's safe to take a look.  The test failures are preexisting and unrelated.

Thanks in advance!

**Comment by devoncarew** [comment]
I have a PR out that would make this PR build cleanly -

**Comment by pq** [comment]
> I have a PR out that would make this PR build cleanly -

Nice.  Just saw that.

**Comment by pq** [comment]
It'll be great to have appveyor green again. 👍

**Comment by keertip** [comment]
lgtm!

**Pull request merged**
