### PR TITLE
Change the placeholder string for search to 'Search API Docs'

### PR DESCRIPTION
**Pull request by gspencergoog**
Fixes flutter/website#1541

### CODE REVIEW

**Comment by gspencergoog** [comment]
Yeah, I tried to do that and got this. Any idea why?:

```
update-test-package-docs: parsing /usr/local/google/home/gspencer/code/public-dart-sdk-stable/dart-sdk/lib/html/html_common/metadata.dart...
update-test-package-docs:
update-test-package-docs: Generation failed: NoSuchMethodError: The getter 'element' was called on null.
update-test-package-docs: Receiver: null
update-test-package-docs: Tried calling: element
update-test-package-docs: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
update-test-package-docs: #1      GenericInferrer._matchInterfaceSubtypeOf.guardedInterfaceSubtype (package:analyzer/src/generated/type_system.dart:493:29)
update-test-package-docs: #2      GenericInferrer._matchInterfaceSubtypeOf (package:analyzer/src/generated/type_system.dart:511:32)
update-test-package-docs: #3      GenericInferrer._matchSubtypeOf (package:analyzer/src/generated/type_system.dart:656:14)
update-test-package-docs: #4      GenericInferrer.tryMatchSubtypeOf (package:analyzer/src/generated/type_system.dart:271:20)
update-test-package-docs: #5      GenericInferrer.constrainReturnType (package:analyzer/src/generated/type_system.dart:136:5)
update-test-package-docs: #6      StrongTypeSystemImpl.inferGenericFunctionOrType (package:analyzer/src/generated/type_system.dart:905:16)
update-test-package-docs: #7      ResolverVisitor._inferArgumentTypesForGeneric (package:analyzer/src/generated/resolver.dart:5809:17)
update-test-package-docs: #8      ResolverVisitor._inferArgumentTypesForInvocation (package:analyzer/src/generated/resolver.dart:5884:25)
update-test-package-docs: #9      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:5373:5)
update-test-package-docs: #10     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7793:49)
update-test-package-docs: #11     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11373:19)
... [ goes on for many frames ]
```

This is using the latest stable Dart SDK, but the same thing happens for the dev SDK.

**Comment by jcollins-g** [comment]
You might have a stale version of analyzer in your pubspec.lock; clear that and try again?

**Comment by gspencergoog** [comment]
So, I tried getting rid of the `pubspec.lock` files, and that didn't change anything.  So I then tried nuking all the top level directories and doing git reset --hard, and I created an empty directory and pointed `PUB_CACHE` to it, and exported `PUB_CACHE`.  I still get the same thing, so I'm pretty sure it's not that something is stale. Any other ideas?

**Comment by gspencergoog** [comment]
Cause determined: I wasn't running `pub get` in the dartdocs directory before trying to update the docs, and the analyzer had a bug in the version I was using.

**Pull request merged**
