### PR TITLE
Add option to exclude source in output

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
FYI @alan-knight 

I think we should set this as the default for the SDK docs, too.

**Comment by keertip** [comment]
@kevmoo , so show no source for SDK docs?

**Comment by keertip** [comment]
lgtm

**Comment by kevmoo** [comment]
@keertip this patch doesn't affect the behavior of --sdk-docs at all – but we might want to consider changing the script on the bots

**Comment by keertip** [comment]
@kevmoo , know this patch does not affect the behavior of other flags. Wanted to know the reason why you think we should not show the source for sdk docs. From #1035, it looks like there are cases where it does not offer any value, but does this apply to most of the source in the sdk?

**Comment by kevmoo** [comment]
Often it's not helpful -> https://api.dartlang.org/1.13.0/dart-convert/Converter/fuse.html

In this case it's a bit nice – https://api.dartlang.org/1.13.0/dart-core/Object/operator_equals.html – but in general it seems like more noise than value.

**Comment by alan-knight** [comment]
I find that with the current layout it really grabs the eye, and the method signature, which is most often what I'd want to know, is hard to see. I can get it from the source, which works for me, but it's more work to parse it out, and it's probably not great for people who aren't used to reading the SDK sources.

**Pull request merged**
