### PR TITLE
Add Github Actions workflow

### PR DESCRIPTION
**Pull request by athomas**

### CODE REVIEW

**Comment by jcollins-g** [comment]
about the only thing left seems to be coverage.  The main bot should be trying to do so, but for some reason it looks like COVERAGE_TOKEN isn't set?

**Comment by athomas** [comment]
> about the only thing left seems to be coverage. The main bot should be trying to do so, but for some reason it looks like COVERAGE_TOKEN isn't set?

I pushed a new change that should fix that.

**Review by jcollins-g — APPROVED** [review]
I can't shut off appveyor issuing errors until we've landed this, so it can't go green.  However, this LGTM now.

**Review by parlough — APPROVED** [review]

**Comment by athomas** [comment]
FYI, I need to revisit the coveralls integration in the new year. Converted this to draft until I checked that what I'm doing is OK.

**Comment by athomas** [comment]
I've updated the branch protection settings to make the use of coveralls compliant with go/github-actions.

**Review by jcollins-g — APPROVED** [review]

**Review by parlough — APPROVED** [review]

**Comment by jcollins-g** [comment]
Landing as the appveyor failure is expected.

**Pull request merged**
