### PR TITLE
Fix void as a type parameter by rewriting most of element_type.dart

### LINKED ISSUE #1625: Dartdoc crashes on "Future<void> foo()"
The Dart language now allows `Future<void>`, and the type of dart:io RandomAccessFile.close() has been changed to that in commit
44aa9a17fd8ca5278dfe12590ad48212fefda4dd

`Future<void> close();` instead of
`Future<RandomAccessFile> close();`

This causes a crash in line 176 of src/element_type.dart, where f.element.library is tested against null, to special-case `A<dynamic>`.  But with `A<void>`, `f.element` is itself null.  If we change to `f.element?.library != null`, we get a crash in the call to `ModelElement.from(f.element, lib)`, again, where there is special casing for dynamic, but not for void.

Flutter code is being changed to use `Future<void>`, and this IO change should also land, so we need to handle this case.

Reverting 44aa9a17fd8ca5278dfe12590ad48212fefda4dd until this is fixed and rolled to Dart SDK

The builder with the failure is:
https://ci.chromium.org/buildbot/client.dart/dart-sdk-linux-be/19230

@jcollins-g 
@jcollins-g: edited to escape types

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #1625.   As mentioned in that bug, the amount of "if (type) do_thing;" spread throughout `ElementType `(not to mention the different meanings of its methods in different contexts) was making it too hard to rationalize about the intended behavior to try to extend it again for void as a type parameter.

Instead, I've refactored and split ElementType into a set of subclasses and got almost all the if type stuff moved into a factory constructor.  This should result in more-or-less identical behavior to the old version, except now, `Future<void>` and anything else with a `void` type parameter should function correctly.  The subclasses are roughly paralleling the class structure of DartType in the analyzer near the root, with changes appropriate to dartdoc's needs.   It's not perfect, but perfect is the enemy of good and I wanted to get this out as quickly as I could.

One minor behavior change is that code that didn't specify a type at all for something where there's no type inference will be documented as "dynamic" rather than having no listed type.

### CODE REVIEW

**Comment by devoncarew** [comment]
Is this ready for review?

**Comment by jcollins-g** [comment]
I think it's ready for a start.  There's a niggling regression on Flutter I haven't quite ironed out yet.

**Comment by jcollins-g** [comment]
This should be ready for a serious look now.  Added @bwilkerson in case he'd like to comment on the new object model.  Definitely open to suggestions though I might defer some of them; I sadly had to do this redesign in a hurry for the P0.

**Comment by jcollins-g** [comment]
@kevmoo I'd like your input on the impact of sprinkling `dynamic` in more places; specifically, in (non-type) parameters.  It's particularly noticeable in `operator==` inherited from Object. 

screenshot from 2018-03-12 10-59-08


I introduced it by accident in the element_type rewrite and I can find a way to get rid of that, but I actually find the docs more readable this way.  It's clear then that this is a dynamic parameter rather than some other inferred type (which if you're looking at the code it can sometimes be hard to tell).

**Comment by kevmoo** [comment]
I think it's okay...do you have other examples?

**Comment by jcollins-g** [comment]
@kevmoo:

We now show it as a return-type from a function parameter:

screenshot from 2018-03-12 10-59-08

And, as a type for a parameter to an optional function parameter:

screenshot from 2018-03-12 11-28-26

**Comment by kevmoo** [comment]
I think it's okay. Run with it and get feedback?

**Comment by jcollins-g** [comment]
will do :-)

**Pull request merged**
