### PR TITLE
rev the dep on http_parser

### PR DESCRIPTION
**Pull request by devoncarew**
- rev the dep on `http_parser` to capture a fix in its pubspec.yaml file (unblock https://github.com/dart-lang/dartdoc/pull/1273)

@jcollins-g

### CODE REVIEW

**Comment by jcollins-g** [comment]
Why not rev pubspec.yaml to force it to pick the right one?

**Comment by devoncarew** [comment]
We don't have a direct dep in `http_parser` currently - it's a transitive dep. We could add a dependency just to be able to specify a min. version.

dartdoc is one of the rarer tools that checks in its pubspec.lock file, so this seemed like a good place to put the fix, but we could just as easily put it in the pubspec.yaml file. I'll move it over.

**Comment by devoncarew** [comment]
Updated!

**Comment by jcollins-g** [comment]
This looks like what I was about to send a PR for locally, just not quite as fast as you yet :-)

LGTM.

I noticed you put an upper bound constraint; presumably any upper bounds are taken care of in the transitive dependencies?  And forgive my questions, still learning norms here for how this works.

**Comment by devoncarew** [comment]
> I noticed you put an upper bound constraint; presumably any upper bounds are taken care of in the transitive dependencies? And forgive my questions, still learning norms here for how this works.

Yup, the constraint solver will try to work out a solution given all the constraints you specify and the constraints your deps specify. In terms of the upper bound, `http_parser` is only guaranteeing to have a stable API between major version releases. We could say we accept the next major release as well, but because it's not out yet, we don't know whether that API will be compatible with what we use (Dart's package manager makes heavy use of [semver](http://semver.org/) ).

**Comment by devoncarew** [comment]
merged! If you update master and then rebase your branch (or merge master into it) you should see a green build.

**Pull request merged**
