### PR TITLE
updated dependencies

### PR DESCRIPTION
**Pull request by kevmoo**
causes dramatic speed increase with analyzer 0.27.1+1

...like 3x faster. Nice! CC @pq

### CODE REVIEW

**Comment by kevmoo** [comment]
...if you use `--no-include-source`

**Comment by keertip** [comment]
yes, thanks to caching doc comments in the analyzer. Thanks @pq !

@kevmoo , so  #1065  is no longer needed?

lgtm!

**Comment by kevmoo** [comment]
Correct!

**Comment by pq** [comment]
> ...like 3x faster. Nice! CC @pq

:+1:

**Pull request merged**
