### PR TITLE
Use deps.dev for OpenSSF scorecard results link

### PR DESCRIPTION
**Pull request by parlough**
This is linked to by the OpenSSF scorecard badge at the top of the README. The previous link was to unformatted JSON. Instead, this links to [deps.dev](https://deps.dev) which formats the results and in the future may include other information.

Previous link: https://api.securityscorecards.dev/projects/github.com/dart-lang/dartdoc
New link: https://deps.dev/project/github/dart-lang%2Fdartdoc

### CODE REVIEW

**Comment by jcollins-g** [comment]
A resync should fix the test errors.

**Comment by jcollins-g** [comment]
adding @devoncarew as a reviewer; I don't know what this link is or what it is for exactly so I'm not sure I can say for sure that this is correct.  The new destination definitely looks better, though.

**Comment by devoncarew** [comment]
That 2nd page does look better. Do you have another example of a repo (dart or flutter) linking to deps.dev, or, does securityscorecards.dev have a more user-friendly URL / page? cc @sealesj

**Comment by parlough** [comment]
> Do you have another example of a repo (dart or flutter) linking to deps.dev, or, does securityscorecards.dev have a more user-friendly URL / page?

Yep, I believe all the Flutter repositories (with scorecards) do, for example [flutter/flutter](https://github.com/flutter/flutter). Recently we requested the dart-lang repos with scorecards be added so we could link there too, for example, [dart-lang/linter](https://github.com/dart-lang/linter#linter-for-dart) and [dart-lang/site-www](https://github.com/dart-lang/site-www#-the-dart-language-site-dartdev). 

securityscorecards.dev does not have a user-friendly page yet: https://github.com/ossf/scorecard-webapp/issues/206

**Pull request merged**
