### PR TITLE
upgrade analyzer

### LINKED ISSUE #624: upgrade the version of the analyzer used
This will support the current sdk 1.12 dev release, which has moved the location of the _internal/libraries.dart files.

### PR DESCRIPTION
**Pull request by keertip**
@devoncarew 

closes #624

### CODE REVIEW

**Comment by devoncarew** [comment]
lgtm

It looks like for stable sdk versions we don't get the latest analyzer because of env constraints on some packages (like `1.11.1`).

**Comment by keertip** [comment]
Yes, you have to be on 1.12 dev and above to get the latest analyzer. Will hold off on committing this till we have the nav in and publish a version, so that users can still get dartdoc with the latest ui with 1.11 sdk.

**Comment by devoncarew** [comment]
I think you can land this; it's just that on the stable sdk pub will select an older version of the analyzer package.

**Comment by keertip** [comment]
Makes sense.

**Pull request merged**
