### PR TITLE
support sdk extensions in dartdoc

### PR DESCRIPTION
**Pull request by devoncarew**
Add support for sdk extensions to dartdoc. This will allow us to generate docs for sky packages; this is a good fix until the code in analyzer_cli is refactored and generally available.

Fix https://github.com/dart-lang/dartdoc/issues/763.

@keertip @sethladd

### CODE REVIEW

**Comment by devoncarew** [comment]
Also, Sky docs look nice:

screen shot 2015-08-10 at 3 47 17 pm

**Comment by keertip** [comment]
@devoncarew, just uploaded a #805  to do the same!

**Comment by devoncarew** [comment]
Let's land them both!

**Comment by sethladd** [comment]
Should I also land a patch for this? :)

Great work!

**Pull request closed without merging**
