### PR TITLE
Various fixes and tweaks

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
Addresses https://github.com/dart-lang/dartdoc/issues/820

**Comment by sethladd** [comment]
Also addresses https://github.com/dart-lang/dartdoc/issues/831

**Comment by devoncarew** [comment]
lgtm!

**Comment by sethladd** [comment]
Cool... I'm still going :)

**Comment by sethladd** [comment]
Also addresses https://github.com/dart-lang/dartdoc/issues/830

**Comment by keertip** [comment]
lgtm!

**Pull request closed without merging**
