### PR TITLE
Remove the use of AnalysisDriver.addFile

### PR DESCRIPTION
**Pull request by bwilkerson**
@scheglov assures me that this isn't necessary, and that this is likely what's causing the analysis session to be invalidated. The larger set of changes isn't currently working, but this passes all the tests, so I thought it was worth getting it committed separately.

### CODE REVIEW

**Comment by bwilkerson** [comment]
The build is failing because:

    Error: Error when reading 'file:///Users/travis/build/dart-lang/dartdoc/bin/cache/snippets.snapshot': No such file or directory

but I have no idea what that means. Any help tracking this down and fixing it would be welcome.

**Comment by jcollins-g** [comment]
This PR is likely fine; the problem there was introduced by some of the tooling support changes Greg is working on.  I'm going to disable one of the tests until that gets fixed in #1824.

**Comment by bwilkerson** [comment]
Great! Is there any way to force it to try again?

**Comment by jcollins-g** [comment]
Yes; I'll do that once I have a complete solution to the nasty bugs causing the assert failures.

**Comment by bwilkerson** [comment]
Thanks!

**Pull request merged**
