### PR TITLE
Typdefs and bug fixes

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by kevmoo** [comment]
Check you formatting.

https://travis-ci.org/dart-lang/dartdoc/jobs/58030533#L142

:smile:

**Comment by sethladd** [comment]
Hah, that's awesome. You are sneaky.

Is there any automated way to run the formatter, and just commit whatever
formatting it made?

**Comment by kevmoo** [comment]
ideally you'd make sure each commit is formatted – instead of adding another 'format' commit after your work

You could/should wire up each git repo for which you care with this: https://plus.sandbox.google.com/+KevinMoore314/posts/RMeFKTzEQoB

Then you can't commit unless it's formatted

**Comment by sethladd** [comment]
Is there a workflow that's better than "always remember to run format before I send up a PR?"  That is, can I automatically include it in a workflow/set of scripts?

**Comment by kevmoo** [comment]
Not sure how to hack that w/ git tools.

We need this in intelliJ - format on save.

**Comment by keertip** [comment]
We now have format on save in Dart Editor and Eclipse plugins.

**Pull request merged**
