### PR TITLE
Pin bots to 2.0.0-dev.16.0

### LINKED ISSUE #1592: dartdoc no longer analyzes cleanly on dev.17
@scheglov 

Looks like the problem is with constructs like this:
https://github.com/dart-lang/dartdoc/blob/c58f4dd268dadb25fb0ada35de51819d9afdf2cd/lib/src/html/html_generator_instance.dart#L95

Might be because of the inferred type of the template argument to filterNonDocumented.

```
$ grind buildbot
Wrong script snapshot version, expected '5d82aa21085dcd6d9c102151972d2852' found '41bd5eab5c21a0d6a57f3da2d31d9545'
grinder running analyze test test-dartdoc buildbot

analyze
analyze: +  /usr/local/google/home/jcollins/dart/all_sdks/2.0.0-dev.17.0/bin/dartanalyzer --fatal-warnings bin lib test tool
analyze: Analyzing bin, lib, test, tool...
analyze:   error • The getter 'allClasses' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:95:49 • undefined_getter
analyze:   error • The getter 'constructors' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:98:59 • undefined_getter
analyze:   error • The getter 'isCanonical' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:99:28 • undefined_getter
analyze:   error • The getter 'constants' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:103:56 • undefined_getter
analyze:   error • The getter 'isCanonical' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:104:25 • undefined_getter
analyze:   error • The getter 'staticProperties' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:108:56 • undefined_getter
analyze:   error • The getter 'isCanonical' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:109:25 • undefined_getter
analyze:   error • The getter 'propertiesForPages' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:113:56 • undefined_getter
analyze:   error • The getter 'isCanonical' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:114:25 • undefined_getter
analyze:   error • The getter 'methodsForPages' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:118:54 • undefined_getter
analyze:   error • The getter 'isCanonical' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:119:23 • undefined_getter
analyze:   error • The getter 'operatorsForPages' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:123:56 • undefined_getter
analyze:   error • The getter 'isCanonical' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:124:25 • undefined_getter
analyze:   error • The getter 'staticMethods' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:128:54 • undefined_getter
analyze:   error • The getter 'isCanonical' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:129:23 • undefined_getter
analyze:   error • The getter 'enums' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:134:48 • undefined_getter
analyze:   error • The getter 'propertiesForPages' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:136:55 • undefined_getter
analyze:   error • The getter 'operatorsForPages' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:139:55 • undefined_getter
analyze:   error • The getter 'methodsForPages' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:142:53 • undefined_getter
analyze:   error • The getter 'constants' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:147:52 • undefined_getter
analyze:   error • The getter 'properties' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:151:52 • undefined_getter
analyze:   error • The getter 'functions' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:155:52 • undefined_getter
analyze:   error • The getter 'typedefs' isn't defined for the class 'Documentable' at lib/src/html/html_generator_instance.dart:159:51 • undefined_getter
analyze:   error • The getter 'fullyQualifiedNameWithoutLibrary' isn't defined for the class 'Documentable' at lib/src/markdown_processor.dart:496:24 • undefined_getter
analyze:   error • The getter 'fullyQualifiedName' isn't defined for the class 'Documentable' at lib/src/markdown_processor.dart:498:24 • undefined_getter
analyze:   error • The getter 'fullyQualifiedName' isn't defined for the class 'Documentable' at lib/src/markdown_processor.dart:499:41 • undefined_getter
analyze:   error • The getter 'fullyQualifiedNameWithoutLibrary' isn't defined for the class 'Documentable' at lib/src/markdown_processor.dart:500:41 • undefined_getter
analyze: 27 errors found.
```

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #1592.  Force appveyor to use the previous version for now.

### CODE REVIEW

**Comment by jcollins-g** [comment]
Merging TBR to fix bots

**Comment by devoncarew** [comment]
lgtm

**Comment by kevmoo** [comment]
@jcollins-g – you can also pin travis by explicitly give the version, too - https://docs.travis-ci.com/user/languages/dart#Choosing-Dart-versions-to-test-against

**Comment by kevmoo** [comment]
> Force appveyor to use the previous version for now.

Reading the original message. Nevermind 😄

**Pull request merged**
