### PR TITLE
add visualization for deprecated

### PR DESCRIPTION
**Pull request by devoncarew**
Some work towards #355.

screen shot 2015-05-14 at 4 06 41 pm

screen shot 2015-05-14 at 4 06 51 pm

Would love some guidance on this PR. I have added the `{{#isDeprecated}}deprecated{{/isDeprecated}}` template fragment in many of the places where a deprecated style would be appropriate, but am missing it in many more places. Is there a less brute force approach to this?

### CODE REVIEW

**Comment by sethladd** [comment]
First off, AWESOME.

Second, there may be a slightly better way. I see a lot of duplicate here. What about using a "partial" to print the name?

See what I did for _documentation.html.

**Comment by sethladd** [comment]
https://github.com/dart-lang/dartdoc/pull/470

**Comment by devoncarew** [comment]
OK, updated. I used a (very small) partial.

**Comment by sethladd** [comment]
lgtm thank you!

**Pull request merged**
