### PR TITLE
Make section titles lighter (and a bit bigger).

### PR DESCRIPTION
**Pull request by munificent**
Since they don't contain real content, they don't need to stand out
that much. Lightening does that, and making the font a bit bigger makes
it a bit easier to read when you do want to.

Also, darkened the ">" in the breadcrumbs to show that it's not part
of the link.

### CODE REVIEW

**Comment by sethladd** [comment]
Is it easy to add a screenshot?

**Comment by sethladd** [comment]
lgtm

**Comment by munificent** [comment]
I'll do that next time if you'd like. Want me to merge this, or should you?

**Comment by sethladd** [comment]
Thanks! A Cmd-Shift-4 on a mac is a very quick way to grab a section.

meanwhile, I'll smash button.

**Pull request merged**
