### PR TITLE
Include diff in highlightjs pack.

### PR DESCRIPTION
**Pull request by isoos**
Same content as in https://github.com/dart-lang/pub-dev/pull/4945

### CODE REVIEW

**Review by srawlins — APPROVED** [review]

**Comment by isoos** [comment]
(merge at your convenience, I don't have the right to do that)

**Comment by isoos** [comment]
Kind ping: can anybody merge this?

**Comment by srawlins** [comment]
I'm looking at dartdoc today; looking at CI failures and a P1, hopefully can merge today.

**Comment by srawlins** [comment]
Sorry, I think you need a rebase.

**Comment by isoos** [comment]
> Sorry, I think you need a rebase.

Done. CI is passing.

**Comment by isoos** [comment]
Thank you!

**Pull request merged**
