### PR TITLE
More inherited fun

### PR DESCRIPTION
**Pull request by kevmoo**
Leading up to the show/hide UI

A set of related fixes and some cleanup

[Review on Reviewable](https://reviewable.io/reviews/dart-lang/dartdoc/1013)

### CODE REVIEW

**Comment by sethladd** [comment]
Does this change the UI? If so, can you post a screenshot?

**Comment by kevmoo** [comment]
The only UI change is here https://github.com/dart-lang/dartdoc/commit/c0a5547cbf3c2eb1e169f8e8e20f69125e6422f2

This makes sure the sidebar ordering matches the body: constructors before properties

**Comment by kevmoo** [comment]
PTAL @keertip

**Comment by kevmoo** [comment]
PTAL, @keertip

**Comment by keertip** [comment]
lgtm!

**Pull request merged**
