### PR TITLE
Lots of Tweaks

### PR DESCRIPTION
**Pull request by kaendfinger**
- Don't show hidden interfaces in implements section.
- Don't show hidden superclasses in extends section.
- Remove hrefs for unresolved annotations. (It was taking you to a page called 'null')
- Fix urls for references to properties inside method documentation.
- Add a link on method/function pages which will take you to the class/library that defines it.

### CODE REVIEW

**Comment by kaendfinger** [comment]
cc @sethladd @keertip

**Comment by keertip** [comment]
Could you create/reference issues, and add code to fake_package so that all the fixes are captured.

**Comment by kaendfinger** [comment]
@keertip I'll try my best :)

**Comment by kaendfinger** [comment]
@keertip Added issues. What kinds of tests do I need? AFAIK, we don't have generation tests, which is what 99% of this relates to.

**Comment by keertip** [comment]
@kaendfinger, thanks for adding code to the fake package!

**Comment by keertip** [comment]
lgtm!

**Comment by kaendfinger** [comment]
Thanks!

**Pull request merged**
