### PR TITLE
Kevmoo tweaks

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@keertip PTAL

**Comment by keertip** [comment]
@kevmoo, tests are failing.

**Comment by kevmoo** [comment]
@keertip PTAL

**Comment by kevmoo** [comment]
@keertip finally clean here – hopefully with fewer blow-ups on appveyor in the future

**Comment by keertip** [comment]
Looks good :)

**Pull request merged**
