### PR TITLE
change constants to lowercase

### PR DESCRIPTION
**Pull request by devoncarew**
Change constants from upper case to lower case.

### CODE REVIEW

**Comment by keertip** [comment]
lgtm!

**Comment by sethladd** [comment]
Is this a general Dart Style thing, or just a style we're adopting for this project?

**Comment by devoncarew** [comment]
Yeah, this changed at some point (https://www.dartlang.org/articles/style-guide/#prefer-using-lowercamelcase-for-constant-names), and I find it does read better then super loud all caps constnats. Happy to change back -

**Comment by sethladd** [comment]
No need to change back. Thanks for keeping us current!

On Friday, June 12, 2015, Devon Carew <notifications@github.com> wrote:

> Yeah, this changed at some point (
> https://www.dartlang.org/articles/style-guide/#prefer-using-lowercamelcase-for-constant-names),
> and I find it does read better then super loud all caps constnats. Happy to
> change back -
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dartdoc/pull/580#issuecomment-111518411>.
>


-- 
Sent from my Motorola Startac

**Pull request merged**
