### PR TITLE
@hideConstantImplementations by default.

### PR DESCRIPTION
**Pull request by kallentu**
`@hideConstantImplementations` is now removed and applied by default where it was checked before.
Updated the tests and moved them to the `constant_values_test.dart` file.
Removed that directive information on the `README`.

Bug: https://github.com/dart-lang/dartdoc/issues/3564.

---

- [X] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Review by srawlins — APPROVED** [review]
Nice!

**Comment by srawlins** [comment]
Flutter has a check for non-replaced doc directives, as seen in the CI. I think we can just remove that directive from flutter, and then land this, and then cut a release.

**Comment by kallentu** [comment]
Sounds good, I'm on it.

**Comment by kallentu** [comment]
@srawlins Okay, took a while to figure out what flutter needs to pass lol. The PR currently parses and hides the `hideConstantImplementations` directive, but it's not useful.
PTAL and I'll submit, cut a release, make a Flutter PR removing the directive usages + bumping the version and come back to delete this directive fully.

**Review by srawlins — APPROVED** [review]
Nice! This is perfect.

**Pull request merged**
