### PR TITLE
fix links for annotations

### LINKED ISSUE #1012: @Deprecated annotation shows up as raw HTML for static method
https://api.dartlang.org/1.13.0-dev.7.6/dart-html/Element/internalCreateElement.html
screen shot 2015-11-02 at 9 55 04 am

### PR DESCRIPTION
**Pull request by keertip**
closes #1012

### CODE REVIEW

**Comment by sethladd** [comment]
Does this pass a broken test? If not, can we add a test that will catch a regression here?

**Comment by keertip** [comment]
There is no test for this at the moment, working on adding one.

On Fri, Nov 6, 2015 at 8:46 AM, Seth Ladd <notifications@github.com> wrote:

> Does this pass a broken test? If not, can we add a test that will catch a
> regression here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dartdoc/pull/1023#issuecomment-154467875>.
>



-- 
Keerti

**Comment by kevmoo** [comment]
@keertip Points for rebasing your test commit so this is just one commit – happy to show you!

**Comment by keertip** [comment]
@kevmoo Will do that in future!

**Comment by kevmoo** [comment]
You can do it now, too :smile: 

Then do a 'git push --force' to your branch and it'll update your pull request – is magic!

**Comment by sethladd** [comment]
fwiw, using the 'git-reflow' tool makes this easy. when you use `git-reflow deliver` it does all the squashing work and lands it on master, and then deletes your working dir.

My flow is this:

```
git reflow start sl-new-branch
commit
commit
git reflow review
commit
git push 
commit
git push
git reflow deliver
```

**Comment by keertip** [comment]
Thanks for the tip @sethladd , have not used git reflow before. Will try it out.

**Pull request merged**
