### PR TITLE
Fix sidebar links for pub packages

### PR DESCRIPTION
**Pull request by srawlins**
I _believe_ this fixes the sidebar issues in https://github.com/dart-lang/pub-dev/issues/7058. CC @isoos 

I've confirmed that (locally), this keeps working links in Flutter, a pub package, and the Dart SDK.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by isoos** [comment]
Yes, this may fix it. I will also test it on Monday...

**Comment by isoos** [comment]
I have tested this on the fake pub-dev server, and can confirm that it fixes the issue.

**Review by keertip — APPROVED** [review]

**Comment by srawlins** [comment]
@isoos are you working off of pub releases? We've been sitting on 7.0.0-wip for a while but we can pull the trigger. I need to get this latest code into Google internal to vet it, then I can cut a release.

**Comment by parlough** [comment]
I guess I didn't fully follow the issue. Does this affect docs generated with `dart doc` or is it more specific to the replacements that pub makes? If it affects `dart doc`, might be worth releasing 7.0.0 and cherry-picking to 3.2 beta.

**Comment by srawlins** [comment]
Yes, it should affect `dart doc`. I'll be curious to know if it is an existing issue in Dart 3.1.0.

**Comment by isoos** [comment]
> are you working off of pub releases? 

Yes, we import published versions. It can be a prerelease if you wanted to.

**Comment by parlough** [comment]
> I'll be curious to know if it is an existing issue in Dart 3.1.0.

It should be. The dartdoc version in 3.1 (https://github.com/dart-lang/dartdoc/commit/e04a6b309a28498e9221ea45c878beae2aaa7dac) is after the sidebars were split out.

**Edit:** I tested locally with 3.1.3 and the issues are present.

**Pull request merged**
