### PR TITLE
cosmetic changes to the stdout status text

### PR DESCRIPTION
**Pull request by devoncarew**
Purely cosmetic changes to the progress text output while dartdoc is running. Old:

```
Generating Dart API docs into docs
parsing /Users/devoncarew/projects/dartdoc/lib/dartdoc.dart...
parsing /Users/devoncarew/projects/dartdoc/lib/generator.dart...
parsing /Users/devoncarew/projects/dartdoc/lib/resource_loader.dart...
parsing /Users/devoncarew/projects/dartdoc/lib/resources.g.dart...

Parsed 4 libraries in 4.0 seconds.

generating docs/index.html
generating docs/dartdoc/index.html
generating docs/dartdoc/DartDoc_class.html
generating docs/dartdoc/DartDoc/DartDoc.html
generating docs/dartdoc/DartDoc/outputDir.html
generating docs/dartdoc/DartDoc/sdkDocs.html
generating docs/dartdoc/DartDoc/libraries.html
generating docs/dartdoc/DartDoc/sdkReadmePath.html
generating docs/dartdoc/DartDoc/stopwatch.html
generating docs/dartdoc/DartDoc/generateDocs.html
generating docs/dartdoc/NAME.html
generating docs/dartdoc/VERSION.html
generating docs/dartdoc/initGenerators.html
generating docs/dartdoc.generator/index.html
generating docs/dartdoc.generator/Generator_class.html
generating docs/dartdoc.generator/Generator/Generator.html
generating docs/dartdoc.generator/Generator/package.html
generating docs/dartdoc.generator/Generator/out.html
generating docs/dartdoc.generator/Generator/generate.html
generating docs/resource_loader/index.html
generating docs/resource_loader/loadAsString.html
generating docs/resource_loader/loadAsBytes.html
generating docs/resources/index.html
generating docs/resources/RESOURCE_NAMES.html

Documented 4 libraries in 4.7 seconds.
```

new:

```
Generating documentation for 'dartdoc' into docs/.

parsing lib/dartdoc.dart...
parsing lib/generator.dart...
parsing lib/resource_loader.dart...
parsing lib/resources.g.dart...
generating docs/index.html
generating docs/dartdoc/index.html
generating docs/dartdoc/DartDoc_class.html
generating docs/dartdoc/DartDoc/DartDoc.html
generating docs/dartdoc/DartDoc/outputDir.html
generating docs/dartdoc/DartDoc/sdkDocs.html
generating docs/dartdoc/DartDoc/libraries.html
generating docs/dartdoc/DartDoc/sdkReadmePath.html
generating docs/dartdoc/DartDoc/stopwatch.html
generating docs/dartdoc/DartDoc/generateDocs.html
generating docs/dartdoc/NAME.html
generating docs/dartdoc/VERSION.html
generating docs/dartdoc/initGenerators.html
generating docs/dartdoc.generator/index.html
generating docs/dartdoc.generator/Generator_class.html
generating docs/dartdoc.generator/Generator/Generator.html
generating docs/dartdoc.generator/Generator/package.html
generating docs/dartdoc.generator/Generator/out.html
generating docs/dartdoc.generator/Generator/generate.html
generating docs/resource_loader/index.html
generating docs/resource_loader/loadAsString.html
generating docs/resource_loader/loadAsBytes.html
generating docs/resources/index.html
generating docs/resources/RESOURCE_NAMES.html

Documented 4 libraries in 4.7 seconds.
```

### CODE REVIEW

**Comment by sethladd** [comment]
I really like seeing the time it takes to parse/analyze. Can we keep that, somehow?

**Comment by devoncarew** [comment]
Sure, will update the PR.

**Comment by sethladd** [comment]
(note: where you put that output is up to you)

**Comment by devoncarew** [comment]
The latest:

```
Generating documentation for 'dartdoc' into docs/.

parsing lib/dartdoc.dart...
parsing lib/generator.dart...
parsing lib/resource_loader.dart...
parsing lib/resources.g.dart...
Parsed 4 files in 4.0 seconds.

generating docs/index.html
generating docs/dartdoc/index.html
generating docs/dartdoc/DartDoc_class.html
generating docs/dartdoc/DartDoc/DartDoc.html
generating docs/dartdoc/DartDoc/outputDir.html
generating docs/dartdoc/DartDoc/sdkDocs.html
generating docs/dartdoc/DartDoc/libraries.html
generating docs/dartdoc/DartDoc/sdkReadmePath.html
generating docs/dartdoc/DartDoc/stopwatch.html
generating docs/dartdoc/DartDoc/generateDocs.html
generating docs/dartdoc/NAME.html
generating docs/dartdoc/VERSION.html
generating docs/dartdoc/initGenerators.html
generating docs/dartdoc.generator/index.html
generating docs/dartdoc.generator/Generator_class.html
generating docs/dartdoc.generator/Generator/Generator.html
generating docs/dartdoc.generator/Generator/package.html
generating docs/dartdoc.generator/Generator/out.html
generating docs/dartdoc.generator/Generator/generate.html
generating docs/resource_loader/index.html
generating docs/resource_loader/loadAsString.html
generating docs/resource_loader/loadAsBytes.html
generating docs/resources/index.html
generating docs/resources/RESOURCE_NAMES.html
Documented 4 libraries in 4.8 seconds.
```

**Comment by sethladd** [comment]
lgtm!

**Pull request merged**
