### PR TITLE
remove the height constraint on the search box

### PR DESCRIPTION
**Pull request by devoncarew**
- remove the height constraint on the search box

Before this, the text in the search box would be a bit compressed vertically; this allows the text to fit its desired height.

before:

Screen Shot 2022-07-26 at 3 33 43 PM

after:

Screen Shot 2022-07-26 at 3 33 59 PM

cc @klr981

### CODE REVIEW

**Comment by srawlins** [comment]
Is the text in the after shot taller than in the before shot? They look identical, or _maybe_ smaller in the after shot.

**Comment by devoncarew** [comment]
> Is the text in the after shot taller than in the before shot? They look identical, or _maybe_ smaller in the after shot.

:) There's more (vertical) padding around the text in the 2nd image. It's subtle, and probably easier to see in the page itself.

(it looks like https://github.com/dart-lang/dartdoc/pull/3099 needs to land to clear up the CI)

**Comment by srawlins** [comment]
Ah I do see the padding change. I thought I was going crazy, haha.

CI will take some time to clear. I'm still figuring it out. :(

**Comment by devoncarew** [comment]
This PR is green now (I merged master into here in order to fix the CI issues).

**Review by srawlins — APPROVED** [review]

**Comment by srawlins** [comment]
Thanks!

**Pull request merged**
