### PR TITLE
Remove extra space between sentences

### PR DESCRIPTION
**Pull request by jcollins-g**
This seemed to work.  @devoncarew @keertip

### CODE REVIEW

**Comment by keertip** [comment]
Awesome! Lets wait for Travis to be done and them merge.

**Comment by jcollins-g** [comment]
This seems related to https://github.com/dart-lang/http_parser/pull/7/files which I also had trouble with when setting up my environment.  @devoncarew what do you think?

**Comment by devoncarew** [comment]
The failure? Yup. @pq has some work in progress for this. We may need to rev our `pubspec.lock` file to capture those fixes.

**Comment by pq** [comment]
> @pq has some work in progress for this. We may need to rev our pubspec.lock file to capture those fixes.

Yeah.  You can follow the unwinding of that issue on https://github.com/flutter/flutter/issues/6840

**Pull request merged**
