### PR TITLE
links for inherited elements, reduce file generation

### PR DESCRIPTION
**Pull request by keertip**
@sethladd , @devoncarew 

We now link to the inherited element, if in the package. Also reduced the files generated, back to 150 secs to generate sdk docs.

### CODE REVIEW

**Comment by devoncarew** [comment]
Looks like the checkLinks task found some issues (https://travis-ci.org/dart-lang/dartdoc/jobs/78612803#L216); nice validation of the build system :)

**Comment by sethladd** [comment]
Automation FTW! :)

**Comment by keertip** [comment]
Those are false positives - if you look at the generated docs, there are no links generated for anything inherited from Duration, dartdoc uses linkedName to make sure it is in the package, whereas the test is checking href.

**Comment by sethladd** [comment]
First off: awesome for working on this!

Does this handle the case of ExtraSpecialList which extends SpecialList which extends ListBase ? Where would ExtraSpecialList's length property link to?  ListBase? List?

**Comment by sethladd** [comment]
The link checker is opening the HTML file and finding anchor tags. Is the link checker broken (it could be)?

**Comment by keertip** [comment]
Ok, the links are there in the generated pages - they are the "..." in the one liner doc comments. Was going to remove the one line doc if the element was inherited but not in package in the next PR, but will fix that now!

**Comment by sethladd** [comment]
> Was going to remove the one line doc if the element was inherited but not in package

Don't we want the one-line doc for any and all names mentioned on a page?

**Comment by keertip** [comment]
The user has no way to jump to the element page to see more of the docs. So at the least we should not be showing that there is more to see.

**Comment by sethladd** [comment]
@keertip do you have a copy of the docs hosted somewhere that you're now generating with this patch?

**Comment by sethladd** [comment]
I don't see links generated for ExtraSpecialList:

screen shot 2015-09-03 at 10 33 34 am

Can you add a test for this, as we should be generating a link to ExtraSpecialList's length property (for example)

**Pull request merged**
