### PR TITLE
Bug Fix for Resource Loader

### PR DESCRIPTION
**Pull request by kaendfinger**
@sethladd

Found a bug. When you look in global_packages, you didn't account for git sources, so I made a quick fix for it.

### CODE REVIEW

**Comment by sethladd** [comment]
Cool, thanks! Please reformat the code and submit the PR again :)

**Comment by kaendfinger** [comment]
Ok

**Comment by kaendfinger** [comment]
Done :)

**Comment by sethladd** [comment]
Thanks!

**Pull request merged**
