### PR TITLE
Add missing static resource.

### PR DESCRIPTION
**Pull request by gspencergoog**
This adds a missing asset to the resources manifest.
I didn't know I needed to run `pub run grinder index-resources` when I added it...

### CODE REVIEW

**Comment by devoncarew** [comment]
@gspencergoog, is this timely? @jcollins-g is out until next wednesday

**Comment by gspencergoog** [comment]
Well, without it, the play buttons will be missing on [animations on the Flutter doc site](https://master-docs-flutter-io.firebaseapp.com/flutter/dart-ui/StrokeJoin-class.html).  There aren't a lot of them yet, but I'd like to fix it.

**Comment by devoncarew** [comment]
ok, gotcha.

I think to get travis green, you'll need to run `grind update-test-package-docs` (as per https://github.com/dart-lang/dartdoc/blob/master/CONTRIBUTING.md).

**Comment by devoncarew** [comment]
> I didn't know I needed to run pub run grinder index-resources when I added it...

We should likely add a travis check for that, or in-line generation into something else, like `update-test-package-docs`. /cc @jcollins-g

**Comment by gspencergoog** [comment]
Yeah, and a Travis check to make sure that the resource manifest doesn't change if you run `grind index-resources` would be good too.

**Comment by gspencergoog** [comment]
Thanks for the review @devoncarew! (I don't have write access, so you'll have to commit it for me... :-))

**Pull request merged**
