### PR TITLE
ignore html template files

### PR DESCRIPTION
**Pull request by devoncarew**
fix https://github.com/dart-lang/dartdoc/issues/760

@sethladd

### CODE REVIEW

**Comment by sethladd** [comment]
lgtm!

**Comment by sethladd** [comment]
merging with master will fix the build issue.

**Comment by devoncarew** [comment]
@sethladd, reflow was throwing exceptions last night - committing normally.

**Comment by sethladd** [comment]
If you have the exceptions, please file here: https://github.com/reenhanced/gitreflow/issues  They've been quite responsive. Thanks!

**Pull request merged**
