### PR TITLE
update creating source for analyzer

### PR DESCRIPTION
**Pull request by keertip**

### CODE REVIEW

**Comment by keertip** [comment]
@devoncarew

**Comment by sethladd** [comment]
lgtm

thanks!

**Comment by sethladd** [comment]
(what bug does this fix?)

**Comment by devoncarew** [comment]
lgtm

It's for fixing generating docs for the sky package. We normalize references to libraries from relative file paths and self reference package: links.

**Comment by devoncarew** [comment]
Oddly enough, I'm still seeing this issue locally after a pub global activate (getting the latest version) and running `dartdoc`. I _don't_ see it after activation if I instead run `pub global run dartdoc`. Perhaps an older version is cached for me? Or perhaps a path issue.

**Comment by devoncarew** [comment]
Ah! `dartdoc` picks up the version from the sdk, which doesn't have this fix. `pub global activate` picks up the latest latest, which does.

**Pull request merged**
