### PR TITLE
Update README to talk about 'dart doc'

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by srawlins** [comment]
Looks like the tests need a tweak

**Comment by mit-mit** [comment]
You mean generally, or specifically for this PR?

**Comment by parlough** [comment]
This PR: https://github.com/dart-lang/dartdoc/blob/master/test/package_meta_test.dart#L67

**Comment by mit-mit** [comment]
Ah, thanks Parker!

**Comment by parlough** [comment]
Seems a new diagnostic is being triggered with the latest dev builds as well. I can fix that is a separate PR.

**Comment by parlough** [comment]
The fix for the analyzer diagnostic has been merged. If you merge the `master` branch in, I believe the build should pass now :)

**Comment by mit-mit** [comment]
@srawlins this is passing now

**Review by srawlins — APPROVED** [review]

**Pull request merged**
