### PR TITLE
bumped analyzer version to 4.0.0

### PR DESCRIPTION
**Pull request by michaelgobbers**

### CODE REVIEW

**Review by srawlins — APPROVED** [review]

**Comment by michaelgobbers** [comment]
@srawlins Thank you for approving this PR!
However, it seems CI is failing, I've been looking in to logs and it's telling me to run `grind build` because `lib/src/generator/templates.runtime_renderers.dart` needs to be regenerated. However when I do so it seems like it isn't regenerated.

I also noticed that running grinder build won't run out of the box. It seems that the `compile js` step has a wrongly formatted output option.

Is there anything obvious I'm missing here to get this thing merged?

**Comment by srawlins** [comment]
I'll try bumping the file on my end, but you might just try `dart run build_runner build` instead of the grinder command. I think I do not run the grinder command.

**Comment by devoncarew** [comment]
@michaelgobbers - I sent you a PR against this PR: https://github.com/michaelgobbers/dartdoc/pull/1. It regenerates the files - not sure if that address all the failures or not.

**Comment by michaelgobbers** [comment]
@devoncarew Seems like your PR did fix a few things. Still not fully there yet though...

**Comment by srawlins** [comment]
I might also just try my own PR because that CI failure is pretty... weird.

**Comment by michaelgobbers** [comment]
@srawlins I did the version bump, just need the workflow approval.

**Comment by srawlins** [comment]
No idea what the continuing error is. I will investigate.

**Comment by srawlins** [comment]
I suspect a bug in analyzer. https://github.com/dart-lang/sdk/issues/49225

**Comment by srawlins** [comment]
@michaelgobbers sorry for the delay; we have a new analyzer release, 4.2.0. Would you mind setting that as the version to use? We can give this another try.

**Comment by michaelgobbers** [comment]
@srawlins bumped to 4.2.0

**Review by srawlins — APPROVED** [review]

**Comment by srawlins** [comment]
Thanks so much! The CI issues are for deprecations in analyzer 4.2.0, and I'll just handle them in a follow-up PR.

**Pull request merged**
