### PR TITLE
Devoncarew printer

### PR DESCRIPTION
**Pull request by devoncarew**
- extend the `HtmlPrinter` class a bit to make it easier to pass in `class` and `href` attributes
- add tests for `HtmlPrinter`
- some tweaks to dartdoc's documentation

### CODE REVIEW

**Comment by devoncarew** [comment]
@keertip, @sethladd, PTAL :)

**Comment by sethladd** [comment]
It doesn't look like HtmlPrinter is used by dartdoc today. If it's not, we should remove it and put it into a package that does use it. I wouldn't expect dartdoc to provide an HtmlPrinter class, unless its default generator uses it.

**Comment by devoncarew** [comment]
Ah, I didn't realize it wasn't used by `HtmlGenerator`. I updated this PR to remove it -

**Comment by keertip** [comment]
lgtm!

**Pull request merged**
