### PR TITLE
Devoncarew gen script

### PR DESCRIPTION
**Pull request by devoncarew**
- create a tool script (`doc_packages.dart`) to generate docs for published packages. It can do one page of packages at a time (50 packages)
- change the stdout to print as we generate docs for a library, not as we create an individual html file. This can get too verbose for even moderate sized packages.
- fix two issues found when running the tool (NPEs)
- identified one more - will file an issue for it

@keertip @sethladd

### CODE REVIEW

**Comment by devoncarew** [comment]
fix https://github.com/dart-lang/dartdoc/issues/145

Will convert this to gen docs in parallel isolates in a future PR.

**Comment by devoncarew** [comment]
Can we turn off coveralls failing builds?

**Comment by keertip** [comment]
Looks good!

**Comment by sethladd** [comment]
Super cool.

**Pull request merged**
