### PR TITLE
use dart support for travis

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by a14n** [comment]
Not related to this PR (because already there in [build #138](https://travis-ci.org/dart-lang/dartdoc/builds/49258542)) but in the output there seems to be an error that do not make the build fail.

```
  failed: docs not generated
        : testDartdoc (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:29:46)
```

**Comment by sethladd** [comment]
Thank you! I'd like to merge this. Can you update the PR so it will merge cleanly?

**Comment by sethladd** [comment]
Friendly ping. Should we try to merge this?

**Comment by a14n** [comment]
PR rebased. (sorry for the delay, I was on vacations)

**Comment by sethladd** [comment]
Not a problem at all. Hope it was a good one!

**Comment by sethladd** [comment]
cc @devoncarew merged!

**Pull request merged**
