### PR TITLE
remove the scrollbar from the subnav

### PR DESCRIPTION
**Pull request by devoncarew**
fix https://github.com/dart-lang/dartdoc/issues/644

### CODE REVIEW

**Comment by sethladd** [comment]
tested on firefox? curious if that also needs a fix.

**Comment by devoncarew** [comment]
Unfortunately, this is webkit/blink only.

**Comment by sethladd** [comment]
The solution is webkit only, or the problem is webkit only?

**Comment by devoncarew** [comment]
There's a solution on firefox, but it involves nested divs, and assumes that you can know ahead of time the width of the scrollbar.

This solution only addresses the problem for webkit based browsers.

**Comment by sethladd** [comment]
ok, let's land this and open a new issue for firefox.

**Pull request merged**
