### PR TITLE
Add annotations to features

### PR DESCRIPTION
**Pull request by jcollins-g**
This change addresses #1265 with a rearrangement of how the "features" section of italicized text is generated under each method or property.

Changes include:

- Methods are now documented as "async" if they return Future objects or are declared "async".
- Annotations, including custom annotations, are displayed, with the exception of "@override" and "@deprecated" as those are indicated by other means in dartdoc.

A prior version of this change added "const" and "static", but that seems duplicitous given that constants and static properties have independent sections on dartdoc pages.

Screenshots:

screen shot 2017-01-23 at 3 37 10 pm
screen shot 2017-01-23 at 3 36 42 pm

### CODE REVIEW

**Comment by sethladd** [comment]
Sorry, but where is an example of `async`? I'm missing it for some reason...

**Comment by jcollins-g** [comment]
The reason you didn't see it is I forgot to include a screenshot of that.... which is now fixed here:

screen shot 2017-01-24 at 9 15 46 am

**Comment by jcollins-g** [comment]
It looks as though a deprecated annotation leaks through in some circumstances; will fix that shortly.  Also will show an example of @Deprecated; that annotation will show here.

**Comment by sethladd** [comment]
Thanks for the additional screenshot. Curious what the motivation was to show "async" ? We should already show that the method/function returns a Future.

**Comment by jcollins-g** [comment]
Screenshot now showing a "Deprecated" annotation with parameters.

As for async, at first there seemed to be considerable interest to add "all the things" in this field.  Of const, static, and async it is the last one I didn't remove for having duplicate ways to determine it.  I can remove it too, though.  Will do that next.

screen shot 2017-01-24 at 10 04 28 am

**Comment by sethladd** [comment]
I don't think we need to print "async", since we should always show the function returns a Future. But maybe others have opinions here.

**Comment by jcollins-g** [comment]
Dropped async from the features list.

screen shot 2017-01-24 at 10 52 50 am

**Comment by sethladd** [comment]
feature LGTM

@keertip did you want to take a look at the implementation?

**Comment by sethladd** [comment]
Thanks for your contribution!

**Comment by sethladd** [comment]
BTW would this show `@required` ?

**Comment by jcollins-g** [comment]
This won't show @required any differently as the "features" list in dartdoc doesn't apply to parameters and @required is a parameter annotation.

This is what dartdoc looks like for @required:

screen shot 2017-01-30 at 9 15 57 am

**Comment by sethladd** [comment]
Ah, thanks!

**Pull request merged**
