### PR TITLE
Improve error when FLUTTER_ROOT is missing.

### LINKED ISSUE #2279: Invalid argument(s): join(null, "bin", "cache", "dart-sdk"): part 0 was null, but part 1 was not.
while we generating doc this error will come.And I set dart-SDK path ,flutter-SDK path but is not working

### PR DESCRIPTION
**Pull request by srawlins**
This is a re-do, sort of, of #1714, which was broken in #2190. Fixes #2279

### CODE REVIEW

**Comment by devoncarew** [comment]
Interesting - when does dartdoc run `pub get` / ` flutter pub get`?

**Comment by srawlins** [comment]
It looks like it only runs it when `.dart_tool/package_config.json` is not found... Not sure why we voluntarily do it, but it's been in there for at least two years.

**Comment by devoncarew** [comment]
> It looks like it only runs it when `.dart_tool/package_config.json` is not found... Not sure why we voluntarily do it, but it's been in there for at least two years.

Interesting. We should likely change this to hard fail if some set of conditions aren't met, instead of falling back on running pub for the user.

**Comment by srawlins** [comment]
Looks like analyzer is broken at HEAD (~0.40.1-dev)

**Comment by scheglov** [comment]
@bwilkerson There might be an issue with `TargetKind` in the analyzer.

**Comment by srawlins** [comment]
@scheglov Travis turned green.

**Comment by srawlins** [comment]
@scheglov This is ready for review.

**Pull request merged**
