### PR TITLE
upgrade the html package dep

### PR DESCRIPTION
**Pull request by devoncarew**
- upgrade the html package dep
- fix https://github.com/dart-lang/dartdoc/issues/1244

@keertip @whesse

### CODE REVIEW

**Comment by whesse** [comment]
I don't understand why we have the .pubspec.lock file committed into the repo.  Shouldn't this be .gitignored, and not in the repo?  If it is common practice to include this file, then OK, but I didn't think it was.

**Comment by sethladd** [comment]
Previous best practice was to commit the .lock file for apps. Libraries should not have a .lock file committed. Maybe that's changed?

**Comment by whesse** [comment]
Eric says that in general, the pubspec.lock should be committed in the repo for applications, but not for libraries.  But I suppose it doesn't hurt anything for a library - things using the library wouldn't even see it.

**Comment by devoncarew** [comment]
I'm confused - dartdoc is an app; per conventions we should be checking in the lock file, no? 

https://github.com/dart-lang/dartdoc/commit/96fadf092744fcb74b501ac2d3ab7df207b63543#diff-7ed8db171f9d2dbefb97f0043b4eb2ff

**Comment by keertip** [comment]
lgtm

**Pull request merged**
