### PR TITLE
Prepare to publish 0.28.4

### PR DESCRIPTION
**Pull request by bwilkerson**

### CODE REVIEW

**Comment by devoncarew** [comment]
Ah, hold on; I think you'll need to run a script locally to re-gen some files w/ the new version.

**Comment by devoncarew** [comment]
If you run `dart tool/grind.dart build-test-package-docs`, do you see local git changes?

**Comment by bwilkerson** [comment]
No, there were no changed files. But then I would hope there wouldn't be; I didn't change any semantics.

**Comment by devoncarew** [comment]
I think the version number gets written into the files, and we have some generated test lib docs checked in.

From the CI results, try `grind build` instead.

**Comment by bwilkerson** [comment]
Yep, I found that too, and now those two files are updated.

**Pull request merged**
