### PR TITLE
change sidebars to 2 cols and center to 8 cols

### PR DESCRIPTION
**Pull request by jakemac53**
Just floating this as an option, I don't think the sidebars need to be as large as they currently are, but I am sure others might disagree :).

This just applies to larger screens, and resolves https://github.com/dart-lang/dartdoc/issues/775, at least in the case of a full sized browser window.

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks! Can you add some screenshots?

**Comment by jakemac53** [comment]
I added grey background to the right column so you can see the size of it, but that is not actually a propsed change.

Original:
original

Proposed:
new

As you can see it does cause some elipses in the right hand column on long names, but I think there is still more than enough to be useful/searchable on the page. Also google search would still see the full names. Chrome is also smart enough to let you search for the full text on the page even though its cut off with the elipses. For example:

search
:

**Comment by sethladd** [comment]
Nice. Can you merge with origin master?

**Comment by polux** [comment]
Woohoo! Thanks for fixing this @jakemac53, that was my number 1 pet peeve with the new dartdoc :)

**Pull request merged**
