### PR TITLE
use the package:pedantic analysis options

### PR DESCRIPTION
**Pull request by devoncarew**
- use the package:pedantic analysis options

@kevmoo @pq

### CODE REVIEW

**Comment by devoncarew** [comment]
Looks like `package:angular` has bumped their min sdk to `2.2.1-dev.3.0` - it's what's causing our bots to fail. Also, it looks like doc gen on pub.dartlang.org: https://pub.dartlang.org/packages/angular#-versions-tab-

**Comment by kevmoo** [comment]
You should be able to pin angular to the previous version – I'm surprised that version solving failed.

**Comment by kevmoo** [comment]
@devoncarew – bet if you rebase this you'll be good!

**Comment by devoncarew** [comment]
Thanks! Updating now.

**Comment by kevmoo** [comment]
@devoncarew – I kicked travis. you're green!

**Pull request merged**
