### PR TITLE
Rewrite parameter handling and add required named parameters for nnbd

### LINKED ISSUE #2059: Optional function/method parameters incorrectly formatted
Originally filed by @jeffque as google/quiver-dart#575:

The documentation for the function `quiver.core.firstNonNull` is being displayed like this:

```dart
firstNonNull(dynamic o1, [ dynamic o2, [ dynamic o3 dynamic o4 ])
```

with an extra square brakets between `o1` and `o2`. I also noted a lack of comma separating `o3` and `o4` now. Maybe related?

It can be found at least [here](https://pub.dev/documentation/quiver/latest/quiver.core/firstNonNull.html) and [here](https://pub.dev/documentation/quiver/latest/quiver.core/quiver.core-library.html)

But, seeing [the code](https://github.com/google/quiver-dart/blob/a5412e39941343a931e988bee72b8690cc5ed809/lib/core.dart#L27), I would expect something like this

```dart
firstNonNull(dynamic o1, dynamic o2, [ dynamic o3, dynamic o4 ])
```

or this:

```dart
firstNonNull(o1, o2, [ o3, o4 ])
```

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #2059, #2052.

The `linkedParams` / `linkedParamsLines` implementation has turned into a hot mess over time.  This rewrites the parameter rendering to abstract the HTML portion of the rendering and use list items to organize the display of parameters on method pages.  Minimal changes to existing tests have been made to make them pass; at some point, a better suite of tests for the new structure could replace a lot of the cut and paste of literal HTML in model_test.dart.

Screenshots:
new-regexp-con
(compare to https://api.dartlang.org/dev/2.7.0-dev.0.0/dart-core/RegExp/RegExp.html)

new-regexp
(compare to https://api.dartlang.org/dev/2.7.0-dev.0.0/dart-core/RegExp-class.html)

Required parameter in action:
new-b-class

new-b-m1-method

### CODE REVIEW

**Comment by devoncarew** [comment]
It looks like named params are getting a 2x indent; their indent should likely match the indent of regular, required params (for the first screenshot, `{bool multiLine: false` and following).

**Comment by jcollins-g** [comment]
Screen Shot 2019-11-18 at 1 47 48 PM

Done, I liked the other way better visually, but this is more consistent.

**Comment by jcollins-g** [comment]
@devoncarew PTAL?

**Comment by jcollins-g** [comment]
@devoncarew Glad you like it.  @jdkoren and I are coordinating to extract more of the rendering goop out in this manner.

**Pull request merged**
