### PR TITLE
0.9.3

### PR DESCRIPTION
**Pull request by devoncarew**
Rev to `0.9.3` in prep for publishing.

@keertip

### CODE REVIEW

**Comment by keertip** [comment]
Don't see the tests run for this branch. With version change, also have to update the test package docs. There is a `grind` task to do this, cant recall the task name.

**Comment by devoncarew** [comment]
```
grind check-version-matches
grinder running [check-version-matches]

[check-version-matches]

finished in 0.071 seconds.
[~/projects/dartdoc] grind check-changelog-has-version
grinder running [check-changelog-has-version]

[check-changelog-has-version]

finished in 0.084 seconds.
[~/projects/dartdoc] grind update-test-package-docs
grinder running [update-test-package-docs]
```

There's one small change the the gen'd docs (the package version).

**Comment by devoncarew** [comment]
Don't know why the branch isn't running the tests; they pass locally.

**Comment by devoncarew** [comment]
(updated)

**Comment by keertip** [comment]
lgtm

**Pull request merged**
