### PR TITLE
cache .pub-cache on travis

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by sethladd** [comment]
Love it, thanks!

**Comment by kevmoo** [comment]
Very cool, @a14n!

Need ta make this part of the default recipe.

**Comment by sethladd** [comment]
Definitely. Is that possible?

Do we have a default or common travis.sh file?  cc @devoncarew

**Comment by devoncarew** [comment]
This is probably the closest to it: https://github.com/dart-lang/oss_project_templates/blob/master/dart-github-dart-lang/.travis.yml

**Comment by sethladd** [comment]
I see this in my builds now:

screen shot 2015-06-01 at 10 00 14 am

Notice the "changes detected, uploading new archive"... do we expect that?

**Comment by kevmoo** [comment]
Looking at https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/dart.rb

I wonder if we can tweak this here...

**Comment by a14n** [comment]
@kevmoo it's indeed the good place but reading http://docs.travis-ci.com/user/caching/ I don't see any cache active by default. We could eventually add a `cache: pub` and do something like in the python script for pip (see https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/python.rb)...

About the default `.travis.yml`, may I suggest https://gist.github.com/a14n/441101c997ee8f935d9c :)

**Pull request merged**
