### PR TITLE
fix an NPE when generating docs

### PR DESCRIPTION
**Pull request by devoncarew**
Fix https://github.com/dart-lang/dartdoc/issues/719 - fix an NPE encountered when generating docs for a package with no readme.md.

### CODE REVIEW

**Comment by sethladd** [comment]
can we get a test for this?

**Comment by devoncarew** [comment]
added!

**Comment by sethladd** [comment]
Thanks! if you squash these commits, lgtm

**Comment by devoncarew** [comment]
oh the squashing

**Pull request merged**
