### PR TITLE
Add the docs.dart.js.map file to published package

### PR DESCRIPTION
**Pull request by srawlins**
Fixes bug in dartdoc 5.1.1

CC @goderbauer

### CODE REVIEW

**Review by devoncarew — APPROVED** [review]
The map file might also have been listed in the generated resources? If so, we could also remove it from there.

**Comment by srawlins** [comment]
> The map file might also have been listed in the generated resources? If so, we could also remove it from there.

What list is this?

**Comment by devoncarew** [comment]
I was thinking of the files generated from the mustache templates, but I don't see it there. I do see a reference from `lib/src/generator/html_resources.g.dart` however.

**Comment by srawlins** [comment]
Ah I see. Good point. It seems like it should be fine to publish this file though? For error reporting, debugging, developing, etc.

**Comment by devoncarew** [comment]
Yeah, that sounds fine asl well.

**Pull request merged**
