### PR TITLE
Do not reference parameters as children of a TypeParameter

### LINKED ISSUE #2716: Regression for dartdoc 0.45.0 -> 1.0.0: protobuf version 2.0.0 fails
Reproduction steps:
```bash
PACKAGE=protobuf
VERSION=2.0.0

cd $(mktemp -d)
curl -L "https://storage.googleapis.com/pub-packages/packages/$PACKAGE-$VERSION.tar.gz" | tar -xz
# This works
dart pub global activate dartdoc 0.45.0
dart pub global run dartdoc
# This won't work
dart pub global activate dartdoc 1.0.0
dart pub global run dartdoc
```

Stack trace:
```
dartdoc 1.0.0 (/home/jonasfj/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart-2.14.0-293.0.dev.snapshot) failed: Bad state: T extends GeneratedMessage cannot have parameters
#0      ModelElement.parameters (package:dartdoc/src/model/model_element.dart:980:7)
#1      TypeParameter.referenceChildren (package:dartdoc/src/model/type_parameter.dart:75:23)
#2      DefinedElementType.referenceChildren (package:dartdoc/src/element_type.dart:367:20)
#3      Extension.referenceChildren (package:dartdoc/src/model/extension.dart:127:23)
#4      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:112:11)
#5      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:122:25)
#6      _getMatchingLinkElementCommentReferable (package:dartdoc/src/markdown_processor.dart:268:31)
#7      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:964:16)
#8      _makeLinkNode (package:dartdoc/src/markdown_processor.dart:913:16)
#9      new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:1062:14)
#10     LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:1057:34)
#11     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_parser.dart:1085:12)
#12     LinkSyntax.close (package:markdown/src/inline_parser.dart:1028:12)
#13     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:152:29)
#14     InlineParser.parse (package:markdown/src/inline_parser.dart:108:9)
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1111:67)
#16     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1116:9)
#17     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:1101:5)
#18     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:73:21)
#19     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:48:23)
#20     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:40:7)
#21     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:926:43)
#22     _renderExtension_partial_callable_6 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:4690:25)
#23     renderExtension (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:4226:24)
#24     HtmlAotTemplates.renderExtension (package:dartdoc/src/generator/templates.dart:143:7)
#25     DartdocGeneratorBackend.generateExtension (package:dartdoc/src/generator/dartdoc_generator_backend.dart:171:29)
#26     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:122:29)
#27     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#28     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:213:21)
<asynchronous suspension>
#29     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:249:28)
<asynchronous suspension>
#30     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:512:9)
<asynchronous suspension>
```

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #2716

### CODE REVIEW

**Review by devoncarew — APPROVED** [review]
👍

**Comment by isoos** [comment]
Thanks for the fix! Any idea when this will get released?

**Comment by srawlins** [comment]
Sorry I meant to release this ASAP. Let me release today.

**Comment by jjliu15** [comment]
Hi, is there an ETA on when this will get released?
Also will this automatically fix the API docs in the packages here: https://github.com/dart-lang/dartdoc/issues/2716#issuecomment-879723474?

**Comment by isoos** [comment]
@jjliu15: once `dartdoc` gets released, `pub.dev` will include it in the next release of the site (at most 2 weeks, depending on other ongoing work), and the packages will get reanalyzed, the documentation will get recreated.

**Comment by simolus3** [comment]
Has this been released? I'm still getting this error with the latest Dart dev (`2.15.0-24.0.dev (dev)`), as well as `2.14.0-377.7.beta (beta) `.  `2.13.4 (stable)` is the only channel where I'm able to run dartdoc without it crashing.

I also still get this error on [one of my packages](https://pub.dev/documentation/moor/latest/log.txt) uploaded today.

**Comment by isoos** [comment]
@simolus3: I think this has been release, but your exception is a new/different one, filed https://github.com/dart-lang/dartdoc/issues/2755 for it.

**Pull request merged**
