### PR TITLE
client search code: stop event propagation when navigating

### PR DESCRIPTION
**Pull request by kevmoo**
Fixes https://github.com/dart-lang/dartdoc/issues/3172

### CODE REVIEW

**Comment by kevmoo** [comment]
I verified this locally. It's a "big lift", but we really should have interactive tests w/ a browser for some of these things. So much behavior that's completely interactive. We don't want to find breaks when we deploy to dart.dev or flutter.dev!

**Review by srawlins — APPROVED** [review]
🎉  Thanks!

**Comment by devoncarew** [comment]
> It's a "big lift", but we really should have interactive tests w/ a browser for some of these things. So much behavior that's completely interactive. We don't want to find breaks when we deploy to dart.dev or flutter.dev!

This is probably worth tracking as a github issue? This may only be a few days for someone reasonably knowledgable in webdriver testing / whatever the current best practice is. As Kevin says, the alternative is finding breakages once the next version hits our big web properties.

**Comment by srawlins** [comment]
@devoncarew got you covered with https://github.com/dart-lang/dartdoc/issues/3027

**Pull request merged**
