### PR TITLE
Fix for a duplicate nullability suffix in Md renderers

### PR DESCRIPTION
**Pull request by VladimirBrejcha**
It seems to me that this line:

`buf.write(elementType.nullabilitySuffix);`

adds nullabilitySuffix to the string, and then this line:

`wrapNullability(elementType, buf.toString());`

which leads to:

```dart
String wrapNullability(T elementType, String inner) =>
      '$inner${elementType.nullabilitySuffix}';
```

that does exactly the same, which results in duplicate nullability suffix in the resulting string

### CODE REVIEW

**Comment by VladimirBrejcha** [comment]
@googlebot I signed it!

**Comment by jcollins-g** [comment]
Thanks for your contribution, and yep, this looks like a bug!   Will approve/merge once all the checks go green.

**Comment by jcollins-g** [comment]
@VladimirBrejcha It looks like this PR may need an update from head to pass; some changes in the dev SDK required some commits to dartdoc.

**Comment by VladimirBrejcha** [comment]
@jcollins-g I merged latest changes from master

**Review by jcollins-g — APPROVED** [review]

**Pull request merged**
