### PR TITLE
no dupe comments for properties

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @keertip please take a look. thanks!

**Comment by keertip** [comment]
lgtm

**Comment by Javier-Esteban** [comment]
Hi, when I run  pub global activate dartdoc  I still get dartdoc 0.4.0., so I still have the issue...
How can I get the last version of dartdoc?

**Comment by sethladd** [comment]
hm, interesting. I see 0.5.0+3 at https://pub.dartlang.org/packages/dartdoc

Maybe try `pub global deactivate dartdoc` first?

**Comment by Javier-Esteban** [comment]
Nop, after deactivating and activating again, I still get version 0.4.0

pub globaldeactivate dartdoc
Deactivated package dartdoc 0.4.0.

pub global activate dartdoc
Resolving dependencies...
+ analyzer 0.26.1
+ args 0.13.2
+ charcode 1.1.0
+ cli_util 0.0.1+2
+ collection 1.1.1
+ crypto 0.9.0
+ csslib 0.12.1
+ dartdoc 0.4.0 (0.5.0+3 available)
+ glob 1.0.5
+ html 0.12.1+2
+ http 0.11.3
+ http_parser 0.0.2+8
+ logging 0.11.1
+ markdown 0.7.2
+ matcher 0.12.0+1
+ mustache4dart 1.0.10
+ package_config 0.1.1
+ path 1.3.6
+ plugin 0.1.0
+ pub_cache 0.1.0
+ pub_semver 1.2.1
+ quiver 0.21.4
+ source_span 1.1.3
+ stack_trace 1.4.1
+ string_scanner 0.1.3+1
+ utf 0.9.0+2
+ watcher 0.9.7
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.3
Precompiling executables...
Loading source assets...
Precompiled dartdoc:dartdoc.
Activated dartdoc 0.4.0.
Installed executable dartdoc.

**Comment by sethladd** [comment]
oh! 0.5 requires 1.12. Try a 1.12-dev channel, and let us know.

**Comment by Javier-Esteban** [comment]
Ok It worked.
And no duplicate comments for properties now.
Thank you

**Comment by sethladd** [comment]
No problem. Thanks again for the report.

**Pull request closed without merging**
