### PR TITLE
Split existing CSS styles into multiple scss partials

### PR DESCRIPTION
**Pull request by parlough**
This PR doesn't change the styles at all or start to take advantage of sass features for the styles themselves. It just splits the existing styles into multiple scss partials and includes them in the root `web/styles/styles.scss` file. This will help keep related styles together, as was already attempted with inline comments before some parts of the original file.

### CODE REVIEW

**Comment by parlough** [comment]
While this PR doesn't change any of the styles themselves, some ordering might have changed in the compiled file, affecting specificity. So I'll spot check this some more and would appreciate a second pair of eyes :)

**Comment by parlough** [comment]
@srawlins Any thoughts on this PR? Once this lands I'll start taking advantage of sass features and making some style fixes.

**Comment by srawlins** [comment]
Hey @parlough sorry for the delay! I'm doing some other stuff until Thursday, so I should be able to give this a review, and manual testing, on Thursday!

**Comment by srawlins** [comment]
It's funny because I think we really don't use too many styles; hard to check visually but everything looks fine to me. I launched the Dart SDK docs (`dart tool/task.dart serve sdk`) and everything looks good. Clicked around different types of pages.

**Review by srawlins — APPROVED** [review]
I love the organization so much ❤️ .

After reading the code I realized that I hadn't looked at search or mobile / responsive UI. Both looks great!

**Comment by srawlins** [comment]
The only thing that caught my eye was how method signatures look in dark mode:

Screenshot 2024-11-22 at 12 50 36 PM

This is _the same_ as dartdoc main branch, so this PR did not change anything. It just struck me as a very low-contrasting grey-on-dark. Something to look into later. Thanks again!

**Comment by srawlins** [comment]
Merge with main and re-upload?

**Pull request merged**
