### PR TITLE
Refine detection for NNBD cases and tag generated pages with "Null safety"

### LINKED ISSUE #2210: dartdoc should show nullability of elements when experiment enabled
Currently, while we don't crash, we don't show nullability when the experiment is switched on.   If the experiment is enabled and the package is migrated, we should try to show nullable elements with `?`.

- [ ] Fields
- [ ] Methods
- [ ] Parameters
- [ ] Type parameters

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #2210.

This puts in the basic scaffolding for tagging pages that are documenting NNBD interfaces and (mostly) boilerplate for connecting to analyzer's package list parsing support.

Tagging @mehmetf and @jdkoren as this touched PackageMeta and markdown templates, respectively.

More extensive tests will wait for a followup -- it's not vital that every case is covered for the preview.

Screen Shot 2020-05-27 at 2 44 30 PM

### CODE REVIEW

**Comment by mehmetf** [comment]
This is fine. In g3, we will opt to mark `allowsNNBD` as false until we can read this from the new packages specification.

**Comment by kevmoo** [comment]
Do we want to go w/ `null safe` over NNBD? CC @mit-mit

**Comment by mit-mit** [comment]
Yes, please never use the term 'NNDB' externally. The external name is 'null safety'.

We recently added tags on pub.dev, I suggest we align [with that](https://github.com/dart-lang/pub-dev/pull/3626/files#diff-961978e7d4be4901da8f10d73183ded8R56), so the tag should say 'Null safety' and the tool-tip should say 'Supports the null safety language feature.'.

**Comment by jcollins-g** [comment]
@mit-mit @kevmoo

Updated the feature tag appearance, text, and tool-tip to align with pub.dev.

Screen Shot 2020-05-28 at 9 41 00 AM

**Comment by mit-mit** [comment]
Awesome, thanks

**Pull request merged**
