### PR TITLE
pub upgrade; readme tweaks

### PR DESCRIPTION
**Pull request by devoncarew**
- run pub upgrade
- tweak some docs

### CODE REVIEW

**Comment by keertip** [comment]
@devoncarew , can we wait on the pub upgrade? Would like to get #904 fixed and running on the bots. The pub upgrade might need tweaking of the dependent packages on the bots. Prefer to do that after the fix is in.

Thanks!

**Comment by devoncarew** [comment]
Sure - reverted the changes to the lock file.

**Comment by keertip** [comment]
Thanks!

**Comment by devoncarew** [comment]
(rebased)

**Pull request merged**
