### PR TITLE
use travis containers

### PR DESCRIPTION
**Pull request by kevmoo**
Faster to boot up

### CODE REVIEW

**Comment by kevmoo** [comment]
FYI @devoncarew – this can help travis turn around a lot faster. They use docker containers so they can avoid booting an entire VM for each run.

**Comment by devoncarew** [comment]
Cool; I remember turning this on for a project, but ended up turning it off (can't recall the reason why). I'll give this another shot; I have been bit by long latency waiting for builds to start up.

**Comment by devoncarew** [comment]
lgtm; I changed the two dartpad projects over

**Comment by sethladd** [comment]
Thanks!

**Pull request closed without merging**
