### PR TITLE
Sanitize HTML output of user-provided markdown content.

### PR DESCRIPTION
**Pull request by isoos**
Part of https://github.com/dart-lang/pub-dev/issues/1418

### CODE REVIEW

**Comment by isoos** [comment]
Part of the CI failure was the version change, which I've reverted as I have no idea what needs to be done to do it.

**Comment by jonasfj** [comment]
Looks more like we're failing:
> dart2-model_test.dart: 03:42 +8 -1: HTML Injection when allowed can inject HTML [E]
> dart2-model_test.dart: 03:42 +8 -2: HTML Injection when allowed can inject HTML from tool [E]

**Comment by isoos** [comment]
When I run the test locally, I've got a simple `documentation` String in one of the failing tests, but when it is run on CI, it gets a different String. How does the testing of this work? Do I need to setup some kind of local environment upfront?

**Comment by devoncarew** [comment]
Is this PR still active?

**Comment by isoos** [comment]
@devoncarew I'd need more insight and help on why the testing fails, but I'd be happy to fix the failing tests if it is possible to do easily.

**Comment by keertip** [comment]
@isoos , can you rebase your PR?

The test that fails is the inject HTML using tool test - https://github.com/dart-lang/dartdoc/blob/master/test/model_test.dart#L334., and the code under test is https://github.com/dart-lang/dartdoc/blob/master/testing/test_package/lib/example.dart#L601. What might be happening is that the html is sanitized  before the injection is done, and so loses the information needed to successfully inject the html.

**Comment by isoos** [comment]
@keertip: rebased. Any idea how I should update the test to make them pass?

**Pull request closed without merging**
